config/routes.rb
Rails.application.routes.draw do
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
  resources :cocktails, only: [ :index, :show, :new, :create ] do
  resources :doses, only: [ :new, :create ]
  end
  delete '/doses/:id', to: 'doses#destroy', as: 'dose'
  root 'cocktails#index'
  mount Attachinary::Engine => "/attachinary"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
    validates :name, presence: true, uniqueness: true

   has_many :doses
    self.abstract_class = true
end

app/models/coktail.rb
class Coktail < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_attachment :photo
end

app/models/dose.rb
class Dose < ApplicationRecord
  belongs_to :cocktail
  belongs_to :ingredient

  validates :description, presence: true
  validates :cocktail_id, uniqueness: { scope: :ingredient_id }
end

app/models/ingredient.rb
class Ingredient < ApplicationRecord
  validates :name, presence: true, uniqueness: true
  has_many :doses, dependent: :destroy
  has_many :ingredients, through: :doses
  has_attachment :photo
end

app/controllers/application_controller.rb
require "application_responder"

class ApplicationController < ActionController::Base
  self.responder = ApplicationResponder
  respond_to :html

  protect_from_forgery with: :exception
end

app/controllers/coktails_controller.rb
class CocktailsController < ApplicationController
  before_action :set_cocktail, only: [ :show ]

  def index
    @cocktails = Cocktail.all
  end

  def show
    @dose = Dose.new
  end

  def new
    @cocktail = Cocktail.new
  end

  def create
    @cocktail = Cocktail.new(cocktail_params)
    if @cocktail.save
      redirect_to cocktails_path
    else
      render :new
    end
  end

  private

  def set_cocktail
    @cocktail = Cocktail.find(params[:id])
  end

  def cocktail_params
    params.require(:cocktail).permit(:name, :photo)
  end
end

app/controllers/doses_controller.rb
class DosesController < ApplicationController
  # def new
  #   @cocktail = Cocktail.find(params[:cocktail_id])
  #   @dose = Dose.new
  # end

  def create
    @cocktail = Cocktail.find(params[:cocktail_id])
    @dose = Dose.new(dose_params)
    @dose.cocktail = @cocktail
    if @dose.save
      redirect_to cocktail_path(@cocktail)
    else
      @review = Review.new
      render "cocktails/show"
    end
  end

  def destroy
    @dose = Dose.find(params[:id])
    @dose.destroy
    redirect_to cocktail_path(@dose.cocktail)
  end

  private

  def dose_params
    params.require(:dose).permit(:description, :ingredient_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/coktails_helper.rb
module CoktailsHelper
end

app/helpers/doses_helper.rb
module DosesHelper
end

app/views/coktails/_card.hmtl.erb
<div class="col-xs-12 col-sm-4">
  <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)), url('<%= bg_path %>');">
    <div class="card-description">
      <h2> <%= cocktail.name  %> </h2>
    </div>
    <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
  </div>
</div>

app/views/coktails/index.html.erb
<div class="container pad20">
  <!-- Heading -->
  <h1 class="text-underline text-brand">Binge cocktails</h1>

    <!-- Grid row -->
  <div class="row">
    <!-- Card -->
    <% @cocktails.each do |cocktail| %>

    <div class="col-xs-12 col-sm-4">
      <div class="card" style="background-image: linear-gradient(rgba(0,0,0,0.3), rgba(0,0,0,0.2)),
                  url('<%= image_or_stub(cocktail, "xmnekrv7t2gigbpgsgtk") %>');">
        <div class="card-description">
          <h2> <%= cocktail.name  %> </h2>
        </div>
        <%= link_to "", cocktail_path(cocktail), class: "card-link" %>
      </div>
    </div>
    <% end %>
  </div>

  <!-- Add button -->
  <div class="pad10">
    <%= link_to "Add your cocktail", new_cocktail_path, class: "btn btn-primary pad20" %>
  </div>

<!-- Close main div -->
</div>

app/views/coktails/new.html.erb
<div class="container padded">
  <h1 class="text-center">Add a cocktail</h1>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
        <%= simple_form_for @cocktail do |f| %>
          <%= f.input :name %>
          <%= f.input :photo, as: :attachinary  %>
          <%= f.submit "Submit", class: "btn btn-primary" %>
        <% end %>
        <div class="pad20">
          <%= link_to "Go back", cocktails_path, class: "btn btn-warning btn-sm" %>
        </div>
    </div>
  </div>
</div>

app/views/coktails/show.html.erb
<div class="container pad20">

  <!-- Heading -->
  <h1 class="text-underline"> <%= @cocktail.name %> </h1>

  <!-- Image -->
  <% if @cocktail.photo? %>
    <%= cl_image_tag @cocktail.photo.path, width: 250, height: 300, crop: :fill %>
  <% end %>

  <!-- Ingredient heading -->
  <div class="pad10">
    <% if @cocktail.doses.empty? %>
    <p class="text-gray">
      No ingredients yet. Add yours!
    </p>
    <% else %>
    <h3> Ingredients </h2>
      <% end %>
  </div>

  <!-- Ingredient list -->
  <ul class="list-unstyled pad20">
    <% @cocktail.doses.each do |d| %>
    <li>
      <i class="fa fa-glass"></i> <strong> <%= d.ingredient.name %> </strong>
      <%= link_to "Delete", dose_path(d), class: "btn btn-danger btn-xs", method: :delete  %>
    </li>
    <p class="pad10"><%= d.description %></p>
    <% end %>
  </ul>
  <div class="pad20">
    <%= link_to "Add ingredient", new_cocktail_dose_path(@cocktail), class: "btn btn-primary", id: "ingredient-add-button"%>
    <%= link_to "Go back", cocktails_path, class: "btn btn-warning" %>
  </div>


    <!-- Add cocktail form -->
    <div class="pad20" id="ingredient-form">
      <div class="row">
        <div class="col-xs-12 col-md-4">
          <%= simple_form_for [@cocktail, @dose] do |f| %>
            <%= f.input :ingredient, collection: Ingredient.order(:name),  prompt: "Pick one from list" %>
            <%= f.input :description %>
            <%= f.submit "Submit", class: "btn btn-primary" %>
          <% end %>
        </div>
      </div>
    </div>

</div>

app/views/doses/new.html.erb
<div class="container padded">
  <h3 class="text-center">Add ingredient...</h1>
  <div class="row">
    <div class="col-xs-12 col-md-6 col-md-offset-3">
      <%= simple_form_for [@cocktail, @dose] do |f| %>
      <%= f.input :ingredient, collection: Ingredient.order(:name), prompt: "Pick one from list" %>
      <%= f.input :description %>
      <%= f.submit "Submit", class: "btn btn-primary" %>
      <% end %>
      <div class="pad20">
        <%= link_to "Go back", cocktails_path, class: "btn btn-warning btn-sm" %>
      </div>
    </div>
  </div>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>RailsMisterCocktail</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
    <%= cloudinary_js_config %>
     <meta name="viewport" content="width=device-width, initial-scale=1">
     <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  </head>

  <body>
    <%= yield %>
  </body>
</html>